id = "path-server-lsp"
name = "Path Server"
version = "1.3.1"
schema_version = 1
authors = ["kunlinglio"]
description = "Path Intellisense like extension for zed, provides fast, real-time file path auto-completion in any language, powered by Path Server."
repository = "https://github.com/kunlinglio/path-server"

[language_servers.path-server-lsp]
name = "path-server-lsp"
languages = [
  "AsciiDoc",
  "Astro",
  "Bash",
  "Biome",
  "C",
  "C#",
  "C++",
  "Clojure",
  "CSharp",
  "CSS",
  "CSV",
  "Crystal",
  "D",
  "Dart",
  "Deno",
  "Docker",
  "Elixir",
  "Elm",
  "Emmet",
  "Erlang",
  "Fish",
  "FSharp",
  "GDScript",
  "Git Commit",
  "Gleam",
  "GLSL",
  "Go",
  "GraphQL",
  "Groovy",
  "Haskell",
  "HEEX",
  "HTML",
  "Hy",
  "Idris",
  "Java",
  "JavaScript",
  "JSON",
  "JSONC",
  "Julia",
  "Kotlin",
  "LaTeX",
  "Lua",
  "Luau",
  "Makefile",
  "Markdown",
  "MDX",
  "Nim",
  "Nix",
  "OCaml",
  "PHP",
  "Plain Text",
  "Prisma",
  "Proto",
  "PureScript",
  "Python",
  "R",
  "Racket",
  "Rego",
  "reST",
  "ReStructuredText",
  "Roc",
  "Ruby",
  "Rust",
  "Scala",
  "Scheme",
  "SCSS",
  "Shell Script",
  "SQL",
  "Svelte",
  "Swift",
  "TailwindCSS",
  "Terraform",
  "TOML",
  "TSX",
  "TypeScript",
  "Typst",
  "Uiua",
  "Vue",
  "Vue.js",
  "WIT",
  "XML",
  "YAML",
  "Yarn",
  "Zig",
]
