name: Release

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

jobs:
  # Step 1: Check and Test
  call_test:
    name: Check and Test before Release
    uses: ./.github/workflows/test.yaml

  # Step 2: Build Rust Binaries and VS Code Extensions
  build:
    name: Build ${{ matrix.vscode_target }}
    needs: call_test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
            vscode_target: linux-x64
          - os: ubuntu-latest
            rust_target: aarch64-unknown-linux-gnu
            vscode_target: linux-arm64
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
            vscode_target: win32-x64
          - os: windows-latest
            rust_target: aarch64-pc-windows-msvc
            vscode_target: win32-arm64
          - os: macos-latest
            rust_target: x86_64-apple-darwin
            vscode_target: darwin-x64
          - os: macos-latest
            rust_target: aarch64-apple-darwin
            vscode_target: darwin-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross-compilation Tools (Linux ARM64)
        if: matrix.rust_target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Build Rust Target
        run: |
          rustup target add ${{ matrix.rust_target }}
          cargo build --release --target ${{ matrix.rust_target }}
        shell: bash

      - name: Prepare Binaries and Package VSIX
        run: |
          mkdir -p dist
          mkdir -p extensions/vscode/bin

          EXE_SUFFIX=""
          if [[ "${{ matrix.rust_target }}" == *"windows"* ]]; then
            EXE_SUFFIX=".exe"
          fi
          BINARY_PATH="target/${{ matrix.rust_target }}/release/path-server$EXE_SUFFIX"

          cp "$BINARY_PATH" "dist/path-server_${{ github.ref_name }}_${{ matrix.rust_target }}$EXE_SUFFIX"
          cp "$BINARY_PATH" "extensions/vscode/bin/path-server$EXE_SUFFIX"
        shell: bash

      - name: Install VS Code Extension Dependencies
        working-directory: ./extensions/vscode
        run: npm install

      - name: Check VS Code Extension Version
        working-directory: ./extensions/vscode
        shell: bash
        run: |
          EXTENSION_VERSION=$(node -p "require('./package.json').version")
          if [ "v$EXTENSION_VERSION" != "${{ github.ref_name }}" ]; then
            echo "Extension version $EXTENSION_VERSION does not match tag ${GITHUB_REF_NAME}"
            exit 1
          fi

      - name: Package VS Code Extension
        working-directory: ./extensions/vscode
        run: npm run build -- --target ${{ matrix.vscode_target }} -o
          ../../dist/path-server_vscode_${{ matrix.vscode_target }}_${{
          github.ref_name }}.vsix

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: release-assets-${{ matrix.vscode_target }}
          path: dist/*

  # Step 3: Create Release on GitHub
  release-github:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          body: |
            See the [CHANGELOG.md](./CHANGELOG.md) for details.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Step 4: Release to crates.io
  release-crates-io:
    name: Release to crates.io
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install toml-cli and Check version
        run: |
          cargo install toml-cli
          test "v$(toml get -r Cargo.toml package.version)" = "${{github.ref_name}}"

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # Step 5: Publish Zed Extension (TODO)
  release-zed-extension:
    name: Publish Zed Extension
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install toml-cli and Check version
        run: |
          cargo install toml-cli
          test "v$(toml get -r extensions/zed/Cargo.toml package.version)" = "${{github.ref_name}}"
          test "v$(toml get -r extensions/zed/extension.toml version)" = "${{github.ref_name}}"
