name: Check and Test

on:
  pull_request:
    branches: [ master ]
  workflow_call:
jobs:
  check-rust:
    name: Format and Clippy Path Server and Zed Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install cargo-audit
        uses: taiki-e/install-action@cargo-audit

      - name: Check for Path Server
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-features -- -D warnings
          cargo audit --deny warnings

      - name: Check for Zed Extension
        working-directory: ./extensions/zed
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-features -- -D warnings
          cargo audit --deny warnings

  check-typescript:
    name: Check VSCode Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: ./extensions/vscode
        run: npm install

      - name: Check types for VS Code Extension
        working-directory: ./extensions/vscode
        run: npm run check-types
      - name: Lint VS Code Extension
        working-directory: ./extensions/vscode
        run: npm run lint

  # Test Path Server on 3 platforms
  test-path-server:
    name: Test Path Server on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests in debug mode
        run: cargo test --all-features

      - name: Run tests in release mode
        run: cargo test --release --all-features
